"""
Phase 6 — Synthetic Demo Dataset Seeding

Provides realistic synthetic demo safety reports representing 5 distinct pattern families:
- Family A (Hero): Pin/component ejection & Line of Fire precursor accumulation (4 reports)
- Family B: Hydraulic hose leakage & pressure release (4 reports)
- Family C: Suspended load & crane rigging path exposure (3 reports)
- Family D: Vehicle movement & pedestrian exposure (3 reports)
- Family E: Unrelated routine safety observations & maintenance (5 reports)
"""

from datetime import date, time
from typing import List
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.models.reports import Report
from app.schemas.enums import ProvenanceType
from app.utils.logging import logger

SYNTHETIC_DEMO_REPORTS = [
    # ── FAMILY A: HERO PIN EJECTION / LINE OF FIRE (4 Reports, Same Asset FL-RIG-DEC-04) ──
    {
        "report_id": "SYN-2026-001",
        "source_system_id": "SRC-SYNTHETIC-101",
        "report_date": date(2026, 8, 15),
        "report_time": time(14, 30, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Drilling Rig 4",
        "shift": "DAY",
        "functional_location": "FL-RIG-DEC-04",
        "functional_location_description": "Main Deck Rigging Floor Skid",
        "item_no": "ITM-9912",
        "incident_type": "Near Miss",
        "incident_sub_type": "Dropped Object / Ejected Component",
        "incident_cause": "Improper Material Handling",
        "fixed_short_description": "Retaining pin ejected under tension near rigger",
        "line_item": "LI-001",
        "narrative": "During removing pin from a structure, one rigman hammered the pin to remove it and it came out at speed passing nearby to the rigman standing opposite to it.",
        "corrective_action": "Work stopped immediately. Retaining clip replaced with double-locking split pin assembly.",
        "preventive_action": "Mandatory pre-use inspection of shackle pins across all deck units.",
        "man_hours": 12.5,
        "lost_time": 0.0,
        "operational_time_lost": 1.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Rigger Level 2",
        "contractor_name": "Apex Offshore Rigging Ltd",
        "actual_outcome": "Near Miss - No bodily injury",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 1,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-006",
        "source_system_id": "SRC-SYNTHETIC-106",
        "report_date": date(2026, 8, 18),
        "report_time": time(10, 15, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Drilling Rig 4",
        "shift": "DAY",
        "functional_location": "FL-RIG-DEC-04",
        "functional_location_description": "Main Deck Rigging Floor Skid",
        "item_no": "ITM-9916",
        "incident_type": "Near Miss",
        "incident_sub_type": "Component Ejection",
        "incident_cause": "IMPROPER PROCEDURE",
        "fixed_short_description": "Component ejected toward opposite rigger during bracket dismantling",
        "line_item": "LI-006",
        "narrative": "While dismantling structural support bracket, worker hammered retaining pin and component was ejected toward opposite rigger standing nearby.",
        "corrective_action": "Tension relief tool enforced prior to pin removal.",
        "preventive_action": "Tooling upgrade across platform rig floor.",
        "man_hours": 10.0,
        "lost_time": 0.0,
        "operational_time_lost": 1.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Rigman",
        "contractor_name": "Apex Offshore Rigging Ltd",
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 6,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-007",
        "source_system_id": "SRC-SYNTHETIC-107",
        "report_date": date(2026, 8, 22),
        "report_time": time(15, 0, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Drilling Rig 4",
        "shift": "DAY",
        "functional_location": "FL-RIG-DEC-04",
        "functional_location_description": "Main Deck Rigging Floor Skid",
        "item_no": "ITM-9917",
        "incident_type": "Near Miss",
        "incident_sub_type": "Unexpected Release",
        "incident_cause": "EQUIPMENT FAILURE",
        "fixed_short_description": "Locking pin shot out crossing technician line of fire",
        "line_item": "LI-007",
        "narrative": "Unexpected release occurred during pin removal activity when locking pin shot out crossing technician line of fire.",
        "corrective_action": "Safety exclusion zone marked during pin extraction.",
        "preventive_action": "Update JSA for all structural pin extraction tasks.",
        "man_hours": 14.0,
        "lost_time": 0.0,
        "operational_time_lost": 2.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Maintenance Technician",
        "contractor_name": None,
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 7,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-008",
        "source_system_id": "SRC-SYNTHETIC-108",
        "report_date": date(2026, 8, 28),
        "report_time": time(11, 30, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Drilling Rig 4",
        "shift": "DAY",
        "functional_location": "FL-RIG-DEC-04",
        "functional_location_description": "Main Deck Rigging Floor Skid",
        "item_no": "ITM-9918",
        "incident_type": "Unsafe Act",
        "incident_sub_type": "Line of Fire Positioning",
        "incident_cause": "POOR POSITIONING",
        "fixed_short_description": "Worker positioned within potential trajectory path during heavy pin extraction",
        "line_item": "LI-008",
        "narrative": "Rigger was positioned within potential trajectory path during heavy pin extraction on rig deck skid.",
        "corrective_action": "Worker relocated to safe standing zone.",
        "preventive_action": "Mandatory Line of Fire safety stand-down for rig floor crew.",
        "man_hours": 8.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Rigger",
        "contractor_name": "Apex Offshore Rigging Ltd",
        "actual_outcome": "Unsafe Act Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 8,
        "provenance": ProvenanceType.SYNTHETIC
    },

    # ── FAMILY B: HYDRAULIC HOSE LEAKAGE (4 Reports, Same Asset FL-CRN-HYD-01) ──
    {
        "report_id": "SYN-2026-004",
        "source_system_id": "SRC-SYNTHETIC-104",
        "report_date": date(2026, 8, 22),
        "report_time": time(11, 0, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Crane Deck 1",
        "shift": "DAY",
        "functional_location": "FL-CRN-HYD-01",
        "functional_location_description": "Pedestal Crane Hydraulic Skids",
        "item_no": "ITM-5531",
        "incident_type": "Near Miss",
        "incident_sub_type": "Fluid Leakage / Pressure Release",
        "incident_cause": "POOR MAINTENANCE",
        "fixed_short_description": "High pressure hydraulic hose spray weeping under 200 bar",
        "line_item": "LI-004",
        "narrative": "During crane slewing test, a pinhole leak developed in high pressure hydraulic line (200 bar) spraying mineral oil onto nearby engine housing. Operator shut down power unit immediately.",
        "corrective_action": "Power unit isolated, hose replaced, spill cleaned with absorbent pads.",
        "preventive_action": "Accelerate preventive replacement schedule for flexible hydraulic lines.",
        "man_hours": 10.0,
        "lost_time": 0.0,
        "operational_time_lost": 2.0,
        "financial_implication": 15000.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Crane Operator",
        "contractor_name": "Ocean Lift Services",
        "actual_outcome": "Near Miss - No Injury / Minor Property Cleaned",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 4,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-009",
        "source_system_id": "SRC-SYNTHETIC-109",
        "report_date": date(2026, 8, 24),
        "report_time": time(14, 20, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Crane Deck 1",
        "shift": "DAY",
        "functional_location": "FL-CRN-HYD-01",
        "functional_location_description": "Pedestal Crane Hydraulic Skids",
        "item_no": "ITM-5532",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "Hose Weeping",
        "incident_cause": "WEAR AND TEAR",
        "fixed_short_description": "Weeping oil observed at flexible hydraulic connection",
        "line_item": "LI-009",
        "narrative": "Weeping hydraulic oil observed at flexible hose connection on deck crane power pack skid.",
        "corrective_action": "Fitting tightened and hose flagged for replacement.",
        "preventive_action": "Inspect all flexible connections on crane power pack.",
        "man_hours": 6.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Hydraulic Technician",
        "contractor_name": None,
        "actual_outcome": "Unsafe Condition Reported",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 9,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-010",
        "source_system_id": "SRC-SYNTHETIC-110",
        "report_date": date(2026, 8, 27),
        "report_time": time(9, 40, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Crane Deck 1",
        "shift": "DAY",
        "functional_location": "FL-CRN-HYD-01",
        "functional_location_description": "Pedestal Crane Hydraulic Skids",
        "item_no": "ITM-5533",
        "incident_type": "Near Miss",
        "incident_sub_type": "Hose Burst",
        "incident_cause": "PRESSURE SPIKE",
        "fixed_short_description": "Hydraulic line burst spraying mineral fluid near skid",
        "line_item": "LI-010",
        "narrative": "Hydraulic line burst spraying mineral fluid near skid during heavy load lift preparation.",
        "corrective_action": "Emergency shutoff valve operated immediately.",
        "preventive_action": "Install protective hose sleeve guards on all high pressure lines.",
        "man_hours": 12.0,
        "lost_time": 0.0,
        "operational_time_lost": 3.0,
        "financial_implication": 25000.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Crane Operator",
        "contractor_name": "Ocean Lift Services",
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 10,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-011",
        "source_system_id": "SRC-SYNTHETIC-111",
        "report_date": date(2026, 8, 30),
        "report_time": time(16, 10, 0),
        "site": "Offshore Platform Alpha",
        "unit": "Crane Deck 1",
        "shift": "DAY",
        "functional_location": "FL-CRN-HYD-01",
        "functional_location_description": "Pedestal Crane Hydraulic Skids",
        "item_no": "ITM-5534",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "Fitting Degraded",
        "incident_cause": "CORROSION",
        "fixed_short_description": "High pressure fitting failed during crane operation",
        "line_item": "LI-011",
        "narrative": "High pressure fitting failed during crane operation resulting in localized pressure drop.",
        "corrective_action": "Fitting replaced with stainless steel equivalent.",
        "preventive_action": "Audit fitting metallurgy across marine crane units.",
        "man_hours": 8.0,
        "lost_time": 0.0,
        "operational_time_lost": 1.0,
        "financial_implication": 5000.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Maintenance Lead",
        "contractor_name": None,
        "actual_outcome": "Unsafe Condition Repaired",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 11,
        "provenance": ProvenanceType.SYNTHETIC
    },

    # ── FAMILY C: SUSPENDED LOAD (3 Reports, FL-CRN-LIFT-02) ──
    {
        "report_id": "SYN-2026-012",
        "source_system_id": "SRC-SYNTHETIC-112",
        "report_date": date(2026, 8, 10),
        "report_time": time(13, 0, 0),
        "site": "Gas Processing Terminal Delta",
        "unit": "Offloading Jetty 1",
        "shift": "DAY",
        "functional_location": "FL-JTY-LFT-02",
        "functional_location_description": "Jetty Crane Lifting Deck",
        "item_no": "ITM-7711",
        "incident_type": "Near Miss",
        "incident_sub_type": "Sling Slippage",
        "incident_cause": "IMPROPER RIGGING",
        "fixed_short_description": "Rigging sling slipped during heavy crane lift",
        "line_item": "LI-012",
        "narrative": "Rigging sling slipped along heavy pipe casing during crane lifting operation over jetty deck.",
        "corrective_action": "Load lowered immediately; rubber friction wraps added to sling.",
        "preventive_action": "Rigging plan review for all smooth cylindrical loads.",
        "man_hours": 10.0,
        "lost_time": 0.0,
        "operational_time_lost": 1.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Rigger",
        "contractor_name": "Marine Heavy Lift",
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 12,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-013",
        "source_system_id": "SRC-SYNTHETIC-113",
        "report_date": date(2026, 8, 14),
        "report_time": time(11, 45, 0),
        "site": "Gas Processing Terminal Delta",
        "unit": "Offloading Jetty 1",
        "shift": "DAY",
        "functional_location": "FL-JTY-LFT-02",
        "functional_location_description": "Jetty Crane Lifting Deck",
        "item_no": "ITM-7712",
        "incident_type": "Near Miss",
        "incident_sub_type": "Unbalanced Load",
        "incident_cause": "CENTER OF GRAVITY SHIFT",
        "fixed_short_description": "Load tilted unexpectedly while hoisting equipment",
        "line_item": "LI-013",
        "narrative": "Load tilted unexpectedly while hoisting equipment container near worker access ladder.",
        "corrective_action": "Taglines attached and center of gravity re-evaluated.",
        "preventive_action": "Mandatory tagline requirement on all container lifts.",
        "man_hours": 8.0,
        "lost_time": 0.0,
        "operational_time_lost": 1.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Jetty Supervisor",
        "contractor_name": None,
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 13,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-014",
        "source_system_id": "SRC-SYNTHETIC-114",
        "report_date": date(2026, 8, 19),
        "report_time": time(15, 30, 0),
        "site": "Gas Processing Terminal Delta",
        "unit": "Offloading Jetty 1",
        "shift": "DAY",
        "functional_location": "FL-JTY-LFT-02",
        "functional_location_description": "Jetty Crane Lifting Deck",
        "item_no": "ITM-7713",
        "incident_type": "Unsafe Act",
        "incident_sub_type": "Suspended Load Path",
        "incident_cause": "UNAUTHORIZED ACCESS",
        "fixed_short_description": "Crane slewing caused load oscillation over walkway",
        "line_item": "LI-014",
        "narrative": "Crane slewing caused load oscillation over walkway while contractor walked underneath exclusion zone.",
        "corrective_action": "Walkway barrier gates locked during lifting operations.",
        "preventive_action": "Install automated lifting zone warning lights.",
        "man_hours": 6.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Technician",
        "contractor_name": "Marine Heavy Lift",
        "actual_outcome": "Unsafe Act Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 14,
        "provenance": ProvenanceType.SYNTHETIC
    },

    # ── FAMILY D: VEHICLE MOVEMENT (3 Reports, FL-YRD-TRK-01) ──
    {
        "report_id": "SYN-2026-015",
        "source_system_id": "SRC-SYNTHETIC-115",
        "report_date": date(2026, 8, 12),
        "report_time": time(8, 0, 0),
        "site": "Refinery Complex Beta",
        "unit": "Material Storage Yard",
        "shift": "DAY",
        "functional_location": "FL-YRD-TRK-01",
        "functional_location_description": "Storage Yard Loading Lane",
        "item_no": "ITM-3301",
        "incident_type": "Unsafe Act",
        "incident_sub_type": "Seatbelt Violation",
        "incident_cause": "PROCEDURE VIOLATION",
        "fixed_short_description": "Forklift operated in bay without wearing seatbelt",
        "line_item": "LI-015",
        "narrative": "Forklift operated in loading bay without driver wearing seatbelt during pipe handling.",
        "corrective_action": "Driver instructed to fasten seatbelt immediately.",
        "preventive_action": "Install interlock seatbelts on all yard forklifts.",
        "man_hours": 4.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Forklift Driver",
        "contractor_name": None,
        "actual_outcome": "Unsafe Act Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 15,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-016",
        "source_system_id": "SRC-SYNTHETIC-116",
        "report_date": date(2026, 8, 16),
        "report_time": time(13, 10, 0),
        "site": "Refinery Complex Beta",
        "unit": "Material Storage Yard",
        "shift": "DAY",
        "functional_location": "FL-YRD-TRK-01",
        "functional_location_description": "Storage Yard Loading Lane",
        "item_no": "ITM-3302",
        "incident_type": "Near Miss",
        "incident_sub_type": "Reversing Vehicle",
        "incident_cause": "BLIND SPOT",
        "fixed_short_description": "Pickup truck reversed near pedestrian walkway",
        "line_item": "LI-016",
        "narrative": "Pickup truck reversed near pedestrian walkway without reverse alarm functioning.",
        "corrective_action": "Vehicle taken out of service until alarm repaired.",
        "preventive_action": "Pre-shift vehicle inspection compliance check.",
        "man_hours": 5.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Driver",
        "contractor_name": "Logistics India Ltd",
        "actual_outcome": "Near Miss",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 16,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-017",
        "source_system_id": "SRC-SYNTHETIC-117",
        "report_date": date(2026, 8, 21),
        "report_time": time(10, 0, 0),
        "site": "Refinery Complex Beta",
        "unit": "Material Storage Yard",
        "shift": "DAY",
        "functional_location": "FL-YRD-TRK-01",
        "functional_location_description": "Storage Yard Loading Lane",
        "item_no": "ITM-3303",
        "incident_type": "Unsafe Act",
        "incident_sub_type": "No Spotter",
        "incident_cause": "NO SPOTTER",
        "fixed_short_description": "Mobile crane moved in yard without spotter",
        "line_item": "LI-017",
        "narrative": "Mobile crane moved across yard transit route without dedicated banksman/spotter.",
        "corrective_action": "Crane stopped until banksman assigned.",
        "preventive_action": "Mandatory spotter rule for all mobile crane transit.",
        "man_hours": 6.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Contractor",
        "employee_or_contractor": "Contractor",
        "designation": "Crane Driver",
        "contractor_name": "Logistics India Ltd",
        "actual_outcome": "Unsafe Act Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 17,
        "provenance": ProvenanceType.SYNTHETIC
    },

    # ── FAMILY E: UNRELATED ROUTINE OBSERVATIONS (5 Reports) ──
    {
        "report_id": "SYN-2026-002",
        "source_system_id": "SRC-SYNTHETIC-102",
        "report_date": date(2026, 8, 18),
        "report_time": time(9, 15, 0),
        "site": "Refinery Complex Beta",
        "unit": "Hydrocracker Unit 2",
        "shift": "DAY",
        "functional_location": "FL-HCU-VAL-12",
        "functional_location_description": "High Pressure Line Testing Area",
        "item_no": "ITM-4410",
        "incident_type": "Unsafe Act",
        "incident_sub_type": "Tool Misuse / Slippage",
        "incident_cause": "USE OF IMPROPER EQUIPMENT",
        "fixed_short_description": "Sledgehammer slipped off valve flange during pressure test prep",
        "line_item": "LI-002",
        "narrative": "Technician used a 10lb sledgehammer to loosen a stuck flange bolt during line testing preparation. The hammer slipped off the nut face and struck the nearby valve guard rail. No hit to personnel.",
        "corrective_action": "Tool replaced with hydraulic torque wrench.",
        "preventive_action": "Enforce SOP requiring hydraulic or pneumatic tools for high-torque flange bolts.",
        "man_hours": 8.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.5,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Maintenance Technician",
        "contractor_name": None,
        "actual_outcome": "Unsafe Act Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 2,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-003",
        "source_system_id": "SRC-SYNTHETIC-103",
        "report_date": date(2026, 8, 20),
        "report_time": time(16, 45, 0),
        "site": "Gas Processing Terminal Delta",
        "unit": "Compressor House 1",
        "shift": "NIGHT",
        "functional_location": "FL-CPH-WALK-02",
        "functional_location_description": "Main Walkway Compressor Room",
        "item_no": "ITM-1092",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "Trip Hazard",
        "incident_cause": "IMPROPER HOUSEKEEPING",
        "fixed_short_description": "Temporary power extension cable laid across main walkway without ramp",
        "line_item": "LI-003",
        "narrative": "Operator noticed a heavy-duty temporary power cable routed across the main primary walking aisle without a rubber cable bridge or warning sign during shift change.",
        "corrective_action": "Cable bridge installed immediately and cable secured.",
        "preventive_action": "Daily housekeeping audit of temporary wiring in operational bays.",
        "man_hours": 6.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Field Operator",
        "contractor_name": None,
        "actual_outcome": "Unsafe Condition Corrected",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 3,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-005",
        "source_system_id": "SRC-SYNTHETIC-105",
        "report_date": date(2026, 8, 25),
        "report_time": time(8, 30, 0),
        "site": "Refinery Complex Beta",
        "unit": "Acid Transfer Station",
        "shift": "DAY",
        "functional_location": "FL-ACD-EYE-03",
        "functional_location_description": "Chemical Loading Bay Safety Station",
        "item_no": "ITM-8820",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "Safety Equipment Failure",
        "incident_cause": "EQUIPMENT BREAKDOWN",
        "fixed_short_description": "Emergency eyewash station water pressure insufficient during routine check",
        "line_item": "LI-005",
        "narrative": "Weekly inspection of emergency eyewash station EW-03 revealed water flow was low and rusty water discharged for 30 seconds before clearing.",
        "corrective_action": "Supply line flushed and pressure regulator cleaned.",
        "preventive_action": "Increase flushing frequency to bi-weekly in corrosive atmosphere areas.",
        "man_hours": 4.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "HSE Inspector",
        "contractor_name": None,
        "actual_outcome": "Safety Equipment Repaired",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 5,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-018",
        "source_system_id": "SRC-SYNTHETIC-118",
        "report_date": date(2026, 8, 26),
        "report_time": time(14, 0, 0),
        "site": "Gas Processing Terminal Delta",
        "unit": "Admin Bay",
        "shift": "DAY",
        "functional_location": "FL-ADM-STAIR-01",
        "functional_location_description": "Admin Building Stairwell",
        "item_no": "ITM-1180",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "Maintenance",
        "incident_cause": "ROUTINE WEAR",
        "fixed_short_description": "Handrail paint touch-up completed in walkway",
        "line_item": "LI-018",
        "narrative": "Routine maintenance touch-up painting of stairwell handrails completed. Caution wet paint sign posted.",
        "corrective_action": "Sign posted.",
        "preventive_action": "Routine facility upkeep.",
        "man_hours": 2.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.0,
        "financial_implication": 0.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Painter",
        "contractor_name": None,
        "actual_outcome": "Routine Maintenance Completed",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 18,
        "provenance": ProvenanceType.SYNTHETIC
    },
    {
        "report_id": "SYN-2026-019",
        "source_system_id": "SRC-SYNTHETIC-119",
        "report_date": date(2026, 8, 29),
        "report_time": time(11, 0, 0),
        "site": "Refinery Complex Beta",
        "unit": "Central Store",
        "shift": "DAY",
        "functional_location": "FL-STR-PPE-01",
        "functional_location_description": "PPE Distribution Store",
        "item_no": "ITM-1190",
        "incident_type": "Unsafe Condition",
        "incident_sub_type": "PPE Replacement",
        "incident_cause": "EXPIRED EQUIPMENT",
        "fixed_short_description": "Safety glasses replaced at store during routine exchange",
        "line_item": "LI-019",
        "narrative": "Scratched safety glasses replaced for technician at store counter during bi-monthly PPE inspection.",
        "corrective_action": "New anti-scratch glasses issued.",
        "preventive_action": "Maintain safety store stock level.",
        "man_hours": 1.0,
        "lost_time": 0.0,
        "operational_time_lost": 0.0,
        "financial_implication": 500.0,
        "currency": "INR",
        "affected_person_type": "Employee",
        "employee_or_contractor": "Employee",
        "designation": "Storekeeper",
        "contractor_name": None,
        "actual_outcome": "PPE Replaced",
        "source_file": "synthetic_seed.csv",
        "source_row_number": 19,
        "provenance": ProvenanceType.SYNTHETIC
    }
]


async def seed_synthetic_reports(db: AsyncSession) -> int:
    """Seeds synthetic demo reports into database if not already present."""
    result = await db.execute(select(Report.report_id))
    existing_ids = set(result.scalars().all())

    seeded_count = 0
    for data in SYNTHETIC_DEMO_REPORTS:
        if data["report_id"] not in existing_ids:
            report_obj = Report(**data)
            db.add(report_obj)
            existing_ids.add(data["report_id"])
            seeded_count += 1

    if seeded_count > 0:
        await db.commit()
        logger.info(f"Seeded {seeded_count} synthetic safety reports into database.")
    else:
        logger.info("Synthetic demo reports already seeded.")

    return seeded_count
